### ISSUE TITLE
Error in generating dataset

### ISSUE THREAD

**Issue by chenqi008** [Singularity42/Sync-DRAW#3]
Hi, Singularity42
I have an error when I generated the dataset. The error is:
/home/chenqi/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "mnist_caption_single.py", line 211, in <module>
    train_data = f['train'].value.reshape(-1, 28, 28)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/chenqi/anaconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'train' doesn't exist)"
Could you tell me how to solve the problem?
Thank you very much.

**Comment by gitzyong812** [comment]
Have you solved this problem?

**Comment by adityavadalkar** [comment]
I am dealing with the same problem. Has anybody found the solution?
